__Importing the libraries__

In [2]:
import pandas as pd
import numpy as np

__Importing the dataset__

In [3]:
dataset = pd.read_csv(r'C:\Users\Toshiba\Documents\datasets\Fish Market dataset.csv')
dataset

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [6]:
x = dataset.iloc[:,2:].values
y = dataset.iloc[:,1].values
print(x)
print(y)


[[23.2    25.4    30.     11.52    4.02  ]
 [24.     26.3    31.2    12.48    4.3056]
 [23.9    26.5    31.1    12.3778  4.6961]
 [26.3    29.     33.5    12.73    4.4555]
 [26.5    29.     34.     12.444   5.134 ]
 [26.8    29.7    34.7    13.6024  4.9274]
 [26.8    29.7    34.5    14.1795  5.2785]
 [27.6    30.     35.     12.67    4.69  ]
 [27.6    30.     35.1    14.0049  4.8438]
 [28.5    30.7    36.2    14.2266  4.9594]
 [28.4    31.     36.2    14.2628  5.1042]
 [28.7    31.     36.2    14.3714  4.8146]
 [29.1    31.5    36.4    13.7592  4.368 ]
 [29.5    32.     37.3    13.9129  5.0728]
 [29.4    32.     37.2    14.9544  5.1708]
 [29.4    32.     37.2    15.438   5.58  ]
 [30.4    33.     38.3    14.8604  5.2854]
 [30.4    33.     38.5    14.938   5.1975]
 [30.9    33.5    38.6    15.633   5.1338]
 [31.     33.5    38.7    14.4738  5.7276]
 [31.3    34.     39.5    15.1285  5.5695]
 [31.4    34.     39.2    15.9936  5.3704]
 [31.5    34.5    39.7    15.5227  5.2801]
 [31.8    3

__Spliting data into Training set and Testing set__

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)


In [21]:
regressor = LinearRegression()
regressor.fit(x_train,y_train,)

LinearRegression()

In [11]:
regressor.intercept_

-492.6608424708786

In [12]:
regressor.coef_

array([ 94.09222371, -31.20371793, -34.50127278,  30.53369148,
        26.22193214])

In [44]:
a = dataset.columns[2:]
b = regressor.coef_
c = pd.DataFrame(b,index = a,columns = ['Coefficients'])
c

Coefficients
Length1     94.092224
Length2    -31.203718
Length3    -34.501273
Height      30.533691
Width       26.221932

In [23]:
regressor.score(x_train,y_train)

0.8961855445576011

__Predicting the Test set results__

In [14]:
y_pred = regressor.predict(x_test)
y_pred

array([ 609.38172383,  636.67107783,  208.52865806,  607.16555366,
       -168.11963362, 1150.4301409 ,  739.88122556,  649.66654433,
       -137.00260773,  556.58465575,  787.10747527,  578.34200166,
        470.47117952,  188.75177584,  449.60359838,  684.68623382,
        179.94912284,  793.85939778,  348.19110298,   99.07595808,
        483.33136667,  454.40417118,  372.55297469,  457.53826094,
        -33.73171351,  370.54212217,  793.81422798, -133.45611514,
        394.23977463,   27.34442848,  306.23808597,  742.23009364])

In [22]:
regressor.score(x_test,y_test)

0.8272507728374039

In [18]:
df = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
df1 = df.head(30) 
df1

Actual    Predicted
0    600.0   609.381724
1    575.0   636.671078
2    150.0   208.528658
3    430.0   607.165554
4      9.7  -168.119634
5   1550.0  1150.430141
6    500.0   739.881226
7    610.0   649.666544
8     13.4  -137.002608
9    500.0   556.584656
10  1000.0   787.107475
11   345.0   578.342002
12   390.0   470.471180
13   145.0   188.751776
14   450.0   449.603598
15   720.0   684.686234
16   130.0   179.949123
17   650.0   793.859398
18   272.0   348.191103
19    85.0    99.075958
20   500.0   483.331367
21   320.0   454.404171
22   273.0   372.552975
23   300.0   457.538261
24    40.0   -33.731714
25   306.0   370.542122
26   920.0   793.814228
27    12.2  -133.456115
28   218.0   394.239775
29    69.0    27.344428

__Predicting the mean of x_train__

In [26]:
xx = np.array((x_train))
xx

array([[24.    , 26.3   , 31.2   , 12.48  ,  4.3056],
       [25.4   , 27.5   , 28.9   ,  7.1672,  4.335 ],
       [26.5   , 29.    , 34.    , 12.444 ,  5.134 ],
       [22.6   , 24.6   , 26.2   ,  6.7334,  4.1658],
       [10.1   , 10.6   , 11.6   ,  1.7284,  1.1484],
       [31.9   , 35.    , 40.5   , 16.2405,  5.589 ],
       [11.5   , 12.2   , 13.4   ,  2.0904,  1.3936],
       [22.    , 24.    , 27.2   ,  7.5344,  3.8352],
       [20.    , 22.    , 23.5   ,  5.5225,  3.995 ],
       [27.6   , 30.    , 35.1   , 14.0049,  4.8438],
       [23.6   , 25.2   , 27.9   ,  7.0866,  3.906 ],
       [16.2   , 18.    , 19.2   ,  5.2224,  3.3216],
       [40.    , 42.5   , 45.5   ,  7.28  ,  4.3225],
       [19.4   , 21.    , 23.7   ,  6.1146,  3.2943],
       [26.3   , 29.    , 33.5   , 12.73  ,  4.4555],
       [30.5   , 32.8   , 34.    , 10.03  ,  6.018 ],
       [31.4   , 34.    , 39.2   , 15.9936,  5.3704],
       [25.2   , 27.3   , 28.7   ,  8.323 ,  5.1373],
       [36.5   , 39.    , 41

In [27]:
xx.shape

(127, 5)

In [28]:
regressor.predict(xx)

array([ 362.41665496,  374.60576277,  437.41664774,  277.1094886 ,
       -190.41585807,  661.88621395, -153.23217049,  220.66362846,
        165.30085706,  511.81341015,  297.79935968,   54.09974171,
        710.6917581 ,  132.85427707,  426.78989419,  644.68327124,
        677.62459184,  425.25701294,  832.94056545,  822.35738741,
        335.7749522 ,  299.64319081,   29.02895228, -251.28395886,
        867.64827278,  546.50298364, -148.32700348,  170.91509269,
        555.47412207,  686.78082509,  223.1285725 ,  293.69726917,
         19.7033007 ,   90.79543567,  248.07807318,  898.56303959,
        542.11419556, -215.45126484,  384.19796821,  762.43395719,
        -91.66353105,  262.93058714,  133.51666883,  -82.35739821,
        270.29381928,  225.06676089, -152.44917166,  700.37822222,
        163.73967519,  639.6597063 ,   82.29882237,  150.97176033,
        223.77838771,  -91.02194132,  881.60837108,  798.3275185 ,
         20.58922128,  797.55191157,  734.21386003,  232.38381